global:
  ingressSubdomain: mooc-surge-ocp01-cluster-0143c5dd31acd8e030a1d6e0ab1380e3-0000.us-east.containers.appdomain.cloud
  tlsSecretName: mooc-surge-ocp01-cluster-0143c5dd31acd8e030a1d6e0ab1380e3-0000

inventory-management-bff-mhm:
  serviceUrl: "inventory-management-svc-mhm-test-mhm:80"
  replicaCount: 1
  
  ingress:
    enabled: true
    tlsSecretName: mooc-surge-ocp01-cluster-0143c5dd31acd8e030a1d6e0ab1380e3-0000

